use anyhow::Result;
use url::Url;

use crate::{
    page::{
        DocumentStartScript, EmulatedMediaOverrides, RendererInspectorSessionRestoreSnapshot,
        RendererMainDocumentCommit, RuntimeBindingRegistration, SubresourceResourceType,
        ViewportSurface,
    },
    runtime::{
        BuiltDocumentPage, CommittedDocumentResourceSource, ExternalRawDocumentBodyStream,
        NavigationPageStorageHandles, PageVmInitStage, PreparedDocumentPage,
        RendererPageReservationToken, RendererReplyBoundary, RendererReservedServiceWorkerClient,
    },
};

use super::BrowserNavigationOwner;

impl BrowserNavigationOwner {
    #[allow(clippy::too_many_arguments)]
    pub async fn build_active_html_page_from_response(
        &mut self,
        storage: NavigationPageStorageHandles,
        requested_url: Url,
        final_url: Url,
        navigation_initiator_url: Option<Url>,
        redirected: bool,
        redirect_count: usize,
        response_status: u16,
        response_headers: Vec<(String, String)>,
        response_body: String,
        document_start_scripts: Vec<DocumentStartScript>,
        runtime_bindings: Vec<RuntimeBindingRegistration>,
        runtime_inspector_session_restore_snapshots: Vec<RendererInspectorSessionRestoreSnapshot>,
        extra_http_headers: Vec<(String, String)>,
        locale_override: Option<String>,
        timezone_override: Option<String>,
        script_execution_disabled: bool,
        bypass_content_security_policy: bool,
        cpu_throttling_rate: f64,
        emulated_media: EmulatedMediaOverrides,
        viewport_surface: Option<ViewportSurface>,
        network_offline: bool,
        blocked_url_patterns: Vec<String>,
        fetch_subresource_interception_enabled: bool,
        fetch_subresource_interception_resource_type: Option<SubresourceResourceType>,
        root_frame_id: Option<String>,
        main_document_commit: Option<RendererMainDocumentCommit>,
    ) -> Result<BuiltDocumentPage> {
        self.active_engine_mut()
            .build_html_page_from_response_with_storage_and_inspector_session_restores_async(
                storage,
                requested_url,
                final_url,
                navigation_initiator_url,
                redirected,
                redirect_count,
                response_status,
                response_headers,
                response_body,
                document_start_scripts,
                runtime_bindings,
                runtime_inspector_session_restore_snapshots,
                extra_http_headers,
                locale_override,
                timezone_override,
                script_execution_disabled,
                bypass_content_security_policy,
                cpu_throttling_rate,
                emulated_media,
                viewport_surface,
                network_offline,
                blocked_url_patterns,
                fetch_subresource_interception_enabled,
                fetch_subresource_interception_resource_type,
                root_frame_id,
                main_document_commit,
            )
            .await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prepare_active_document_page_from_response(
        &mut self,
        page_reservation: RendererPageReservationToken,
        storage: NavigationPageStorageHandles,
        requested_url: Url,
        final_url: Url,
        navigation_initiator_url: Option<Url>,
        redirected: bool,
        redirect_count: usize,
        response_status: u16,
        response_headers: Vec<(String, String)>,
        response_body: String,
        document_start_scripts: Vec<DocumentStartScript>,
        runtime_bindings: Vec<RuntimeBindingRegistration>,
        runtime_inspector_session_restore_snapshots: Vec<RendererInspectorSessionRestoreSnapshot>,
        extra_http_headers: Vec<(String, String)>,
        locale_override: Option<String>,
        timezone_override: Option<String>,
        script_execution_disabled: bool,
        bypass_content_security_policy: bool,
        cpu_throttling_rate: f64,
        emulated_media: EmulatedMediaOverrides,
        viewport_surface: Option<ViewportSurface>,
        network_offline: bool,
        blocked_url_patterns: Vec<String>,
        fetch_subresource_interception_enabled: bool,
        fetch_subresource_interception_resource_type: Option<SubresourceResourceType>,
        root_frame_id: Option<String>,
        resource_source: CommittedDocumentResourceSource,
        main_document_commit: Option<RendererMainDocumentCommit>,
    ) -> Result<PreparedDocumentPage> {
        self.active_engine_mut()
            .prepare_document_page_from_response_with_storage_and_inspector_session_restores_async(
                page_reservation,
                storage,
                requested_url,
                final_url,
                navigation_initiator_url,
                redirected,
                redirect_count,
                response_status,
                response_headers,
                response_body,
                document_start_scripts,
                runtime_bindings,
                runtime_inspector_session_restore_snapshots,
                extra_http_headers,
                locale_override,
                timezone_override,
                script_execution_disabled,
                bypass_content_security_policy,
                cpu_throttling_rate,
                emulated_media,
                viewport_surface,
                network_offline,
                blocked_url_patterns,
                fetch_subresource_interception_enabled,
                fetch_subresource_interception_resource_type,
                root_frame_id,
                resource_source,
                main_document_commit,
            )
            .await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prepare_active_streaming_raw_page(
        &mut self,
        page_reservation: RendererPageReservationToken,
        storage: NavigationPageStorageHandles,
        requested_url: Url,
        final_url: Url,
        navigation_initiator_url: Option<Url>,
        redirected: bool,
        redirect_count: usize,
        response_status: u16,
        response_headers: Vec<(String, String)>,
        raw_body: ExternalRawDocumentBodyStream,
        document_start_scripts: Vec<DocumentStartScript>,
        runtime_bindings: Vec<RuntimeBindingRegistration>,
        runtime_inspector_session_restore_snapshots: Vec<RendererInspectorSessionRestoreSnapshot>,
        extra_http_headers: Vec<(String, String)>,
        locale_override: Option<String>,
        timezone_override: Option<String>,
        script_execution_disabled: bool,
        bypass_content_security_policy: bool,
        cpu_throttling_rate: f64,
        emulated_media: EmulatedMediaOverrides,
        viewport_surface: Option<ViewportSurface>,
        network_offline: bool,
        blocked_url_patterns: Vec<String>,
        fetch_subresource_interception_enabled: bool,
        fetch_subresource_interception_resource_type: Option<SubresourceResourceType>,
        stage: PageVmInitStage,
        reply_boundary: RendererReplyBoundary,
        root_frame_id: Option<String>,
        resource_source: CommittedDocumentResourceSource,
        reserved_service_worker_client: Option<RendererReservedServiceWorkerClient>,
        main_document_commit: Option<RendererMainDocumentCommit>,
    ) -> Result<PreparedDocumentPage> {
        self.active_engine_mut()
            .prepare_streaming_raw_page_from_external_body_with_storage_and_inspector_session_restores_async(
                page_reservation,
                storage,
                requested_url,
                final_url,
                navigation_initiator_url,
                redirected,
                redirect_count,
                response_status,
                response_headers,
                raw_body,
                document_start_scripts,
                runtime_bindings,
                runtime_inspector_session_restore_snapshots,
                extra_http_headers,
                locale_override,
                timezone_override,
                script_execution_disabled,
                bypass_content_security_policy,
                cpu_throttling_rate,
                emulated_media,
                viewport_surface,
                network_offline,
                blocked_url_patterns,
                fetch_subresource_interception_enabled,
                fetch_subresource_interception_resource_type,
                stage,
                reply_boundary,
                root_frame_id,
                resource_source,
                reserved_service_worker_client,
                main_document_commit,
            )
            .await
    }
}
