[package]
license.workspace = true
name = "moli-page-types"
version = "0.1.0"
edition = "2024"

[features]
test-support = []

[dependencies]
bitflags.workspace = true
moli-cookie-jar.workspace = true
moli-dom.workspace = true
moli-fetch.workspace = true
moli-web-mime.workspace = true
http-auth.workspace = true
regex.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
url.workspace = true

[lints]
workspace = true
