[package]
name = "moli-protocol-server"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["ws"] }
base64.workspace = true
flate2.workspace = true
futures-util.workspace = true
moli-bounded-json.workspace = true
moli-cookie-jar.workspace = true
moli-core.workspace = true
moli-fetch.workspace = true
moli-protocol.workspace = true
moli-protocol-cdp.workspace = true
moli-protocol-webdriver-bidi.workspace = true
moli-protocol-webdriver-classic.workspace = true
moli-trace.workspace = true
parking_lot.workspace = true
percent-encoding.workspace = true
serde_json.workspace = true
socket2 = { workspace = true, features = ["all"] }
tokio = { workspace = true, features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "signal", "sync"] }
tracing.workspace = true
url.workspace = true

[dev-dependencies]
moli-browser-profile.workspace = true
moli-cookie-cache.workspace = true
moli-protocol = { workspace = true, features = ["test-support"] }
png.workspace = true
time.workspace = true
tokio-tungstenite.workspace = true
tower = { workspace = true, features = ["util"] }

[lints]
workspace = true
