[package]
license.workspace = true
name = "moli-dom"
version = "0.1.0"
edition = "2024"

[dependencies]
html5ever.workspace = true
indexmap.workspace = true
moli-css-parse.workspace = true
moli-html-input-temporal.workspace = true
percent-encoding.workspace = true
selectors.workspace = true
serde_json.workspace = true
servo_arc.workspace = true
thin-vec.workspace = true
url.workspace = true

[lints]
workspace = true
