[package]
license.workspace = true
name = "moli-protocol"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
test-support = []

[dependencies]
anyhow.workspace = true
base64.workspace = true
indexmap.workspace = true
moli-bounded-buffer.workspace = true
moli-core.workspace = true
moli-header-field.workspace = true
moli-page-types.workspace = true
moli-browser-profile.workspace = true
moli-cookie-jar.workspace = true
moli-encoding.workspace = true
moli-protocol-cdp.workspace = true
moli-fetch.workspace = true
moli-css-parse.workspace = true
moli-shared-worker.workspace = true
moli-site.workspace = true
moli-storage-key.workspace = true
moli-trace.workspace = true
moli-url.workspace = true
moli-url-policy.workspace = true
moli-v8-platform.workspace = true
moli-web-mime.workspace = true
parking_lot.workspace = true
percent-encoding.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_path_to_error.workspace = true
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "signal", "sync"] }
tracing.workspace = true
url.workspace = true
v8.workspace = true
time.workspace = true
chromiumoxide_cdp.workspace = true
data-url.workspace = true
moli-crypto.workspace = true
http.workspace = true
sanitize-filename.workspace = true

[dev-dependencies]
axum = { workspace = true, features = ["ws"] }
moli-cookie-jar = { workspace = true, features = ["test-support"] }
moli-image.workspace = true
moli-storage-service.workspace = true
moli-v8-init.workspace = true

[build-dependencies]
vergen-gitcl.workspace = true

[lints]
workspace = true
