[package]
name = "moli-paint"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyrender.workspace = true
anyrender_svg = { workspace = true, features = ["text"] }
anyrender_vello_cpu = { workspace = true, features = ["bitmap-glyphs", "filters"] }
moli-image.workspace = true
moli-layout.workspace = true
peniko.workspace = true

[lints]
workspace = true
