[package]
license.workspace = true
name = "moli-selector"
version = "0.1.0"
edition = "2024"

[dependencies]
app_units.workspace = true
cssparser.workspace = true
dom.workspace = true
euclid.workspace = true
moli-css-parse.workspace = true
moli-dom.workspace = true
indexmap.workspace = true
parking_lot.workspace = true
percent-encoding.workspace = true
precomputed-hash.workspace = true
selectors.workspace = true
stylo.workspace = true
style_traits.workspace = true
url.workspace = true

[lints]
workspace = true
