[package]
name = "moli-layout"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
euclid.workspace = true
kurbo.workspace = true
moli-image.workspace = true
parley.workspace = true
parking_lot.workspace = true
stylo.workspace = true
stylo_taffy = { workspace = true, features = ["std", "block", "flexbox", "grid", "floats"] }
taffy = { workspace = true, features = ["std", "block_layout", "flexbox", "grid", "float_layout", "content_size", "calc", "detailed_layout_info"] }
thiserror.workspace = true
wuff.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
yeslogic-fontconfig-sys.workspace = true

[lints]
workspace = true
