[package]
license.workspace = true
name = "moli-cookie-jar"
version = "0.1.0"
edition = "2024"

[features]
default = []
test-support = []

[dependencies]
cookie_store = { workspace = true, features = ["public_suffix"] }
moli-site.workspace = true
moli-storage-key.workspace = true
parking_lot.workspace = true
time.workspace = true
tracing.workspace = true
url.workspace = true

[lints]
workspace = true
