[package]
license.workspace = true
name = "moli-http-cache"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
httpdate.workspace = true
moli-header-field.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
rustc-hash.workspace = true
typed-num = { workspace = true, features = ["serde"] }
url.workspace = true

[lints]
workspace = true
