[package]
license.workspace = true
name = "moli-webidl"
version = "0.1.0"
edition = "2024"

[dependencies]
moli-v8-util.workspace = true
moli-webidl-callback.workspace = true
moli-webidl-derive.workspace = true
v8.workspace = true

[dev-dependencies]
moli-v8-test-util.workspace = true

[lints]
workspace = true
