[package]
license.workspace = true
name = "moli-v8-platform"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-utils.workspace = true
parking_lot.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tracing.workspace = true
v8.workspace = true

[dev-dependencies]
moli-v8-init.workspace = true
serde_json.workspace = true

[lints]
workspace = true
