[package]
license.workspace = true
name = "moli-stylesheet-blocking"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util.workspace = true
moli-dom.workspace = true
moli-fetch.workspace = true
moli-owner-queue.workspace = true
moli-page-types.workspace = true
moli-time.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
url.workspace = true

[lints]
workspace = true
