[package]
license.workspace = true
name = "moli-websocket"
version = "0.1.0"
edition = "2024"

[features]
test-support = ["dep:rcgen", "dep:tokio-rustls", "dep:tokio-tungstenite"]

[dependencies]
base64.workspace = true
bytes.workspace = true
futures-util = { workspace = true, features = ["sink", "std"] }
http.workspace = true
moli-stealth-net.workspace = true
moli-url.workspace = true
rand.workspace = true
ratchet_rs = { workspace = true, features = ["deflate", "split"] }
sha1.workspace = true
rcgen = { workspace = true, features = ["aws_lc_rs"], optional = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-rustls = { workspace = true, features = ["aws_lc_rs", "logging", "tls12"], optional = true }
tokio-tungstenite = { workspace = true, features = ["handshake"], optional = true }
url.workspace = true

[dev-dependencies]
rcgen = { workspace = true, features = ["aws_lc_rs"] }
tokio-tungstenite = { workspace = true, features = ["handshake"] }
tokio-rustls = { workspace = true, features = ["aws_lc_rs", "logging", "tls12"] }

[lints]
workspace = true
