[package]
authors = ["Patrick Fernie <patrick.fernie@gmail.com>"]
name = "moli-cookie-store"
version = "0.22.1"
edition = "2021"
rust-version = "1.88.0"
repository = "https://github.com/pfernie/cookie_store"
documentation = "https://docs.rs/cookie_store"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["cookie", "jar", "store", "http"]  # free text
categories = ["web-programming::http-client", "web-programming"]  # https://crates.io/category_slugs
publish = false

[lib]
name = "cookie_store"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["public_suffix"]

## uses `indexmap::IndexMap` in lieu of HashMap internally, so cookies are maintained in insertion/creation order
preserve_order = ["dep:indexmap"]
## Add support for pluggable public suffix lookups.
public_suffix = ["dep:psl-types"]

## Enable logging the values of cookies marked 'secure', off by default as values may be sensitive
log_secure_cookie_values = []

[dependencies]
document-features.workspace = true
idna.workspace = true
time.workspace = true
url.workspace = true

indexmap = { workspace = true, optional = true }

psl-types = { workspace = true, optional = true }

[dependencies.cookie]
workspace = true

[lints]
workspace = true
