[package]
license.workspace = true
name = "moli-cookie-cache"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
moli-cookie-jar.workspace = true
netscape-cookie-file-parser.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
time.workspace = true
typed-num = { workspace = true, features = ["serde"] }

[lints]
workspace = true
