[package]
name = "moli-image"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
image = { workspace = true, features = ["gif", "webp"] }
jpeg-decoder.workspace = true
jpeg-encoder.workspace = true
png.workspace = true
thiserror.workspace = true
usvg.workspace = true
xmlparser.workspace = true

[lints]
workspace = true
