[package]
license.workspace = true
name = "moli-stealth-net"
version = "0.1.0"
edition = "2024"

[package.metadata.browseroxide-sync]
repository = "https://github.com/yfedoseev/browser_oxide.git"
base-revision = "9cd4af36b744bc8f9047bcceeb341610a6f32109"
source-root = "crates/browser_oxide/src"
imported-paths = ["net"]

[dependencies]
base64.workspace = true
boring2.workspace = true
boring-sys2 = { workspace = true, features = ["prefix-symbols"] }
brotli.workspace = true
bytes.workspace = true
foreign-types.workspace = true
futures-util.workspace = true
http.workspace = true
http2 = { workspace = true, features = ["unstable"] }
httparse.workspace = true
parking_lot.workspace = true
percent-encoding.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-boring2.workspace = true
url.workspace = true
webpki-root-certs.workspace = true

[dev-dependencies]
h2.workspace = true
rcgen = { workspace = true, features = ["aws_lc_rs"] }
tokio-rustls = { workspace = true, features = ["aws_lc_rs", "logging", "tls12"] }

[lints]
workspace = true
